### PR TITLE
Allow claims to be configured

### LINKED ISSUE #14: Proposal for changing sub and adding more claims
### What feature do you want to see added?

Hi and thanks for maintaining this plugin. It's been super useful!

I'd like to propose to slightly change the sub to
* do not include the jenkins address (is this useful for other use cases?)
* Have it in a format similar to gh or gitlab (examples below)

GitLab ([ref](https://docs.gitlab.com/ee/ci/cloud_services/index.html#how-it-works))
```
project_path:mygroup/myproject:ref_type:branch:ref:main
```

GH ([ref](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect))
```
repo:octo-org/octo-repo:environment:prod
```

This way we might use one openid token to serve multiple multiple requests for multiple branches (matching against different SAs)

Following their model it might also be convenient to add more claims, although I don't see it urgent as modifying the sub.

What do you think? Should I send a patch for it? Happy to discuss more!

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by jglick**
System for configurable JWT claims. Closes #14.

Supersedes #15: you can simply change `${JOB_URL}` to `${JOB_NAME}` as you prefer.

Supersedes #16: you can add custom claims for things like `${BRANCH_NAME}`, or include them in `sub`ject in some format.

Precedes #17: `IdTokenCredentials.algorithm` could rather become a property of `IdTokenConfiguration`.

While all of these things _could_ be properties of `IdTokenCredentials` rather than global configuration, I am not confident in the usability of such a system’s security model. As discussed in https://github.com/jenkinsci/oidc-provider-plugin/pull/15#issuecomment-1212091098, this would permit any “disgruntled employee” with folder configuration rights to begin issuing signed id tokens from Jenkins which define completely arbitrary `sub`ject or other claims. While the `iss`uer would either be external to Jenkins or, if the default, not be under the attacker’s control, this puts the onus on administrators configuring OIDC-enabled services (Vault, …) to carefully trust only specific `iss`uers, and be aware that tokens issued from Jenkins not at global scope may not be as trustworthy as those issued at global scope. Since it seems unlikely that a single controller would actually need to issue tokens with two different formats for a particular claim, making this global configuration seems safer.

- [X] sketch of system
- [x] enforce valid claim list
- [x] regression: `build_number` claim supposed to be numeric
- [x] test of GUI
- [x] test of CasC
- [x] test of alternate claims
- [x] form validation
- [x] inline help
- [x] user docs

### CODE REVIEW

**Comment by LucaPrete** [comment]
Can you please also update the docs so users will know how to use this?

**Comment by jglick** [comment]
https://github.blog/changelog/2022-10-18-github-actionsopenid-connect-support-enhanced-to-enable-secure-cloud-deployments-at-scale/ heh

**Comment by fungusakafungus** [comment]
> https://github.blog/changelog/2022-10-18-github-actionsopenid-connect-support-enhanced-to-enable-secure-cloud-deployments-at-scale/ heh

Someone leaked this PR to github actions team! We got a mole!

**Comment by jglick** [comment]
Would anyone interested in this functionality be willing to try a build prior to merge & release? Assuming CI passes, there will be an **Incrementals** link from which you can download a `*.hpi` file to install manually in **Plugin Manager** » **Advanced**.

**Comment by fungusakafungus** [comment]
I'd be happy to test in the next few days

**Comment by jglick** [comment]
Thanks in advance! https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/oidc-provider/38.va_7394b_f3f646/oidc-provider-38.va_7394b_f3f646.hpi

**Comment by kstevena** [comment]
@jglick, I have quickly tested your valuable feature without facing issues.
Here is what I've tested:
- General & build scoped claims of type string with constant values and substitutions (existing and non existing environment variables)
- Global and folder scoped OpenID Connect token credentials
- JCasC apply & export

**Comment by jglick** [comment]
Thanks! The test coverage is also reasonably complete, so what I am really interested in is whether the design is practical with a realistic configuration of an actual service such as Vault or AWS.

**Comment by fungusakafungus** [comment]
Testing it too, setting "primary" claim to `${BRANCH_IS_PRIMARY}` and assuming an aws role with a trust policy like
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<account-id>:oidc-provider/<jenkins-host>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "<jenkins-host>:primary": "true",
                }
            }
        }
    ]
}
```
works well and seems useful

**Comment by jglick** [comment]
Perfect, that is the sort of thing I was looking for; will release. Please feel free to file PRs updating docs with tested real-world examples.

**Comment by LucaPrete** [comment]
This is great! Thanks a lot for the effort.
Sorry for not being able to contribute as well. I'll give it a try soon as
well.

-Luca

Il giorno mar 1 nov 2022 alle ore 14:22 Jesse Glick <
***@***.***> ha scritto:

**Comment by fungusakafungus** [comment]
I'm afraid I wasn't very thorough with AWS testing, I had other conditions in the mix as well, and while trying to simplify the test I found out that claim names are not automatically available as condition keys; the list of available condition keys for AWS policies is here: [Available keys for AWS web identity federation
](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-wif)

This PR is still useful for constructing `sub` claim differently, I will continue testing and document what's possible and useful.

**Comment by bml1g12** [comment]
> names are not automatically available as condition keys; the list of available condition keys for AWS policies is here: [Available keys for AWS web identity federation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-wif)

@fungusakafungus  did you manage to get this working with AWS trust policy? I wonder if there's any way to view what keys are available from cloudtrail or otherwise

**Comment by fungusakafungus** [comment]
> @fungusakafungus did you manage to get this working with AWS trust policy? I wonder if there's any way to view what keys are available from cloudtrail or otherwise

the docs say it's only `sub` for this combination of systems. I didn't get further that this sadly.

**Comment by bml1g12** [comment]
> > @fungusakafungus did you manage to get this working with AWS trust policy? I wonder if there's any way to view what keys are available from cloudtrail or otherwise
> 
> the docs say it's only `sub` for this combination of systems. I didn't get further than this sadly.

I'm struggling to get even `sub` to work - any idea why? I have a repo `org_name/repo_name` so in Jenkins configuttion for Build-scoped claim templates I've configured key: git_url and value: GIT_URL 

image

Then in the trust policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxx:oidc-provider/jenkins.hq.scvl.jp/oidc"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "jenkins.hq.scvl.jp/oidc:aud": "sts.amazonaws.com",
                    "jenkins.hq.scvl.jp/oidc:sub": "git_url:https://github.com/org_name/repo-name.git"
                }
            }
        }
    ]
}
```

But it seems this does not produce a role that can be adopted - any idea why?

**Comment by bml1g12** [comment]
Ah I see what I'm doing wrong, the git_url is a new claim, seperate to sub. Also ${GIT_URL} isn't be substituted correctly.

Can debug by JWT decoding the AWS Web Identity Token being used

**Comment by jglick** [comment]
> Can debug by JWT decoding

Yes, this is something that should probably be highlighted in docs; example: https://github.com/jenkinsci/oidc-provider-plugin/blob/e313d1fecea64213315f6d3d0ede35b3afa26828/demo/aws/run.sh#L162-L172

(Note that `\$` there is escaping for purposes of `configuration-as-code` YAML; a real `Jenkinsfile` should use just `$`.)

You need to be careful, however, that no one has access to the build logs (within an hour of the build running) who cannot be trusted since only the encoded JWT will be masked. In the above example, `..` is used to deliberately suppress masking of even the encoded form, again just for demo purposes.

**Comment by fungusakafungus** [comment]
I use this jq incantation for debugging the token:
`jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' < $AWS_WEB_IDENTITY_TOKEN_FILE`

**Pull request merged**
